apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
    - name: "33060"
      port: 33060
      targetPort: 33060
  selector:
    app: db
status:
  loadBalancer: {}