apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer